/*!
 * Hikebeast /full · i18n runtime (hand-written).
 * Loaded BLOCKING in <head>, AFTER lib/i18n-strings.js (which sets
 * window.HB_I18N = { en:{...}, de:{...}, fr:{...} } with flat dotted keys,
 * generated by scripts/build-i18n.mjs from i18n/*.yaml).
 *
 * Single source of truth for UI-chrome localization. Editorial spot content
 * is localized separately (Phase 2, applyEditorial in social.js).
 *
 * Public surface:
 *   window.t(key, vars)            -> localized string, {var} interpolation, en fallback
 *   window.t.plural(key, n, vars)  -> singular/plural via key.one / key.other
 *   window.hbI18n.lang             -> active 'en' | 'de' | 'fr'
 *   window.hbI18n.apply(root)      -> localize [data-i18n] / [data-i18n-plural] / [data-i18n-attr]
 *   window.hbI18n.setLang(lang)    -> persist hb_lang + reload
 *
 * Language pick: localStorage('hb_lang') -> navigator.languages -> 'en'.
 * Reuses the hb_lang key the sales-page redirect already owns; adds 'fr'.
 */
(function () {
  'use strict';

  var SUPPORTED = ['en', 'de', 'fr', 'it'];
  var DEFAULT = 'en';
  var KEY = 'hb_lang';
  var DICTS = window.HB_I18N || { en: {}, de: {}, fr: {} };

  function readStored() {
    try {
      var v = localStorage.getItem(KEY);
      return SUPPORTED.indexOf(v) >= 0 ? v : null;
    } catch (e) { return null; }
  }

  // Same detection shape as lang-check.html, extended with 'fr'.
  function detect() {
    var stored = readStored();
    if (stored) return stored;
    var langs = (navigator.languages && navigator.languages.length)
      ? navigator.languages
      : (navigator.language ? [navigator.language] : []);
    for (var i = 0; i < langs.length; i++) {
      var l = (langs[i] || '').toLowerCase();
      if (l.indexOf('de') === 0) return 'de';
      if (l.indexOf('fr') === 0) return 'fr';
      if (l.indexOf('it') === 0) return 'it';
      if (l.indexOf('en') === 0) return 'en';
    }
    return DEFAULT;
  }

  var LANG = detect();
  var DICT = DICTS[LANG] || {};
  var EN = DICTS.en || {};

  // FOUC guard: hide static [data-i18n*] nodes until apply() runs, but ONLY
  // when the active language differs from the baked-in English HTML, so English
  // visitors (the no-swap case) never see a hidden flash. Matching CSS rule
  // (html.hb-i18n-pending [data-i18n]{visibility:hidden}) lives in preview.css.
  // Runs synchronously in <head>, before first paint.
  try {
    if (LANG !== 'en') document.documentElement.classList.add('hb-i18n-pending');
    document.documentElement.setAttribute('lang', LANG);
  } catch (e) {}

  function has(obj, k) { return obj && Object.prototype.hasOwnProperty.call(obj, k); }

  function lookup(key) {
    if (has(DICT, key)) return DICT[key];
    if (has(EN, key)) return EN[key];     // fall back to English
    return key;                            // last resort: surface the missing key
  }

  function interp(str, vars) {
    if (!vars) return str;
    return String(str).replace(/\{(\w+)\}/g, function (m, k) {
      return has(vars, k) ? String(vars[k]) : m;
    });
  }

  function t(key, vars) { return interp(lookup(key), vars); }

  t.plural = function (key, n, vars) {
    var suffix = (Number(n) === 1) ? '.one' : '.other';
    var merged = { n: n };
    if (vars) for (var k in vars) if (has(vars, k)) merged[k] = vars[k];
    return interp(lookup(key + suffix), merged);
  };

  // Localize a subtree:
  //   [data-i18n="key"]                 -> textContent = t(key)
  //   [data-i18n-plural="key" data-n=N] -> textContent = t.plural(key, N)
  //   [data-i18n-attr="attr:key;..."]   -> setAttribute(attr, t(key)) per pair
  function apply(root) {
    root = root || document;
    var i, el, list;

    list = root.querySelectorAll('[data-i18n]');
    for (i = 0; i < list.length; i++) {
      el = list[i];
      el.textContent = t(el.getAttribute('data-i18n'));
    }

    list = root.querySelectorAll('[data-i18n-plural]');
    for (i = 0; i < list.length; i++) {
      el = list[i];
      var n = parseInt(el.getAttribute('data-n'), 10);
      el.textContent = t.plural(el.getAttribute('data-i18n-plural'), isNaN(n) ? 0 : n);
    }

    list = root.querySelectorAll('[data-i18n-attr]');
    for (i = 0; i < list.length; i++) {
      el = list[i];
      var pairs = (el.getAttribute('data-i18n-attr') || '').split(';');
      for (var p = 0; p < pairs.length; p++) {
        var idx = pairs[p].indexOf(':');
        if (idx < 0) continue;
        var attr = pairs[p].slice(0, idx).trim();
        var key = pairs[p].slice(idx + 1).trim();
        if (attr && key) el.setAttribute(attr, t(key));
      }
    }
  }

  function setLang(lang) {
    if (SUPPORTED.indexOf(lang) < 0 || lang === LANG) return;
    try { localStorage.setItem(KEY, lang); } catch (e) {}
    // Mirror to a cookie too (cheap) so any future server/middleware logic can
    // read the choice. Not required by the runtime approach.
    try { document.cookie = KEY + '=' + lang + ';path=/;max-age=31536000;samesite=lax'; } catch (e) {}
    location.reload();
  }

  window.HB_I18N = DICTS;
  window.t = t;
  window.hbI18n = {
    lang: LANG,
    supported: SUPPORTED.slice(),
    t: t,
    apply: apply,
    setLang: setLang,
  };

  function run() {
    apply(document);
    try { document.documentElement.classList.remove('hb-i18n-pending'); } catch (e) {}
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', run);
  } else {
    run();
  }
})();
