#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const ORIGIN = "https://hikebeast.ch";

const PAGES = [
  { md: "index.md",         url: "/" },
  { md: "free.md",          url: "/free/" },
  { md: "imprint.md",       url: "/imprint.html" },
  { md: "privacy.md",       url: "/privacy.html" },
  { md: "de/index.md",      url: "/de/" },
  { md: "de/free.md",       url: "/de/free/" },
  { md: "de/imprint.md",    url: "/de/imprint.html" },
  { md: "de/privacy.md",    url: "/de/privacy.html" },
];

const sections = [];
for (const { md, url } of PAGES) {
  const body = (await readFile(join(root, md), "utf8")).trim();
  sections.push(`<!-- source: ${ORIGIN}${url} -->\n\n${body}`);
}

const header = `<!-- Hikebeast llms-full.txt -->
<!-- Generated by scripts/build-llms.mjs. Do not edit by hand. -->
<!-- Concatenation of every page linked from /llms.txt as plain Markdown. -->

`;

const out = header + sections.join("\n\n---\n\n") + "\n";
await writeFile(join(root, "llms-full.txt"), out, "utf8");

const tokens = Math.round(out.length / 4);
console.log(`wrote llms-full.txt: ${PAGES.length} sections, ${out.length} chars, ~${tokens} tokens`);
