#!/usr/bin/env node
//
// Compiles the UI-chrome string catalog i18n/{en,de,fr}.yaml into
// full/lib/i18n-strings.js  (window.HB_I18N = { en, de, fr } with flat dotted
// keys). The runtime core full/lib/i18n.js reads window.HB_I18N.
//
// Enforces KEY PARITY across all three languages: a key present in one file but
// missing in (or extra to) English fails the build. This is the guardrail that
// keeps the languages from silently drifting — the same spirit as the
// tracking-pipeline lint that fails the Vercel build on a dropped field.
//
//   node scripts/build-i18n.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const I18N = join(ROOT, "i18n");
const OUT = join(ROOT, "full", "lib", "i18n-strings.js");
const LANGS = ["en", "de", "fr", "it"];

// Flatten nested yaml maps into dotted keys: { nav: { home: "Home" } } ->
// { "nav.home": "Home" }. Leaf values are coerced to strings.
function flatten(obj, prefix = "", out = {}) {
  for (const [k, v] of Object.entries(obj || {})) {
    const key = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === "object" && !Array.isArray(v)) flatten(v, key, out);
    else out[key] = v == null ? "" : String(v);
  }
  return out;
}

const dicts = {};
for (const lang of LANGS) {
  const raw = yaml.load(readFileSync(join(I18N, `${lang}.yaml`), "utf8"));
  dicts[lang] = flatten(raw);
}

// Parity gate.
const enKeys = Object.keys(dicts.en);
const enSet = new Set(enKeys);
let failed = false;
for (const lang of LANGS) {
  if (lang === "en") continue;
  const set = new Set(Object.keys(dicts[lang]));
  const missing = enKeys.filter((k) => !set.has(k));
  const extra = [...set].filter((k) => !enSet.has(k));
  if (missing.length) {
    failed = true;
    console.error(`[build-i18n] ${lang}.yaml is MISSING ${missing.length} key(s):\n  ${missing.join("\n  ")}`);
  }
  if (extra.length) {
    failed = true;
    console.error(`[build-i18n] ${lang}.yaml has ${extra.length} EXTRA key(s) not in en.yaml:\n  ${extra.join("\n  ")}`);
  }
}
if (failed) {
  console.error("\n[build-i18n] FAILED — key drift across i18n/*.yaml. Fix the catalog so all three languages share one key set.");
  process.exit(1);
}

const banner = "// AUTO-GENERATED by scripts/build-i18n.mjs from i18n/*.yaml — do not edit by hand.\n";
writeFileSync(OUT, banner + `window.HB_I18N = ${JSON.stringify(dicts)};\n`);
console.log(`[build-i18n] wrote ${OUT} — ${enKeys.length} keys × ${LANGS.length} languages.`);
