// Auto-generated by scripts/build-spot-images.mjs.
// Maps a spot key (`<chapter_id>#<anchor>`) to its full photo gallery.
// Index 0 is the primary photo (matches the chapter card's <img>); extras
// follow. Spots with only one photo are NOT listed — the carousel UI
// checks for the key before activating, so single-photo spots fall back
// to the static <img>.
window.HB_SPOT_IMAGES = {
  "central#engstligen_falls": [
    {
      "src": "derivatives/engstligen_falls_p0/w1800.webp",
      "credit": "Anthony Gomez"
    },
    {
      "src": "derivatives/engstligen_falls_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/engstligen_falls_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/engstligen_falls_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#oltschibachfall": [
    {
      "src": "derivatives/oltschibachfall_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/oltschibachfall_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/oltschibachfall_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#rosenlaui": [
    {
      "src": "derivatives/rosenlaui_p0/w1800.webp",
      "credit": "Simon Spring"
    },
    {
      "src": "derivatives/rosenlaui_p1/w1800.webp",
      "credit": "@katerina.trapp"
    },
    {
      "src": "derivatives/rosenlaui_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/rosenlaui_p3/w1800.webp",
      "credit": "@eluakidss"
    }
  ],
  "central#rosenlaui_public_waterfall": [
    {
      "src": "derivatives/rosenlaui_public_waterfall_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/rosenlaui_public_waterfall_p1/w1800.webp",
      "credit": "Jkphotos"
    }
  ],
  "central#rosenlauifall": [
    {
      "src": "derivatives/rosenlauifall_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/rosenlauifall_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#triftbrucke": [
    {
      "src": "derivatives/triftbrucke_p0/w1800.webp",
      "credit": "@petartravel"
    },
    {
      "src": "derivatives/triftbrucke_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#gelmersee": [
    {
      "src": "derivatives/gelmersee_p0/w1800.webp",
      "credit": "Dario Brönnimann"
    },
    {
      "src": "derivatives/gelmersee_p1/w1800.webp",
      "credit": "Simon Infanger"
    },
    {
      "src": "derivatives/gelmersee_p2/w1800.webp",
      "credit": "Lucas Favre"
    },
    {
      "src": "derivatives/gelmersee_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#guttannen_valley": [
    {
      "src": "derivatives/guttannen_valley_p0/w1800.webp",
      "credit": "@shaunaxbst"
    },
    {
      "src": "derivatives/guttannen_valley_p1/w1800.webp",
      "credit": "@shaunaxbst"
    },
    {
      "src": "derivatives/guttannen_valley_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#aare_gorge": [
    {
      "src": "derivatives/aare_gorge_p0/w1800.webp",
      "credit": "Thiva"
    },
    {
      "src": "derivatives/aare_gorge_p1/w1800.webp",
      "credit": "Peter Burdon"
    },
    {
      "src": "derivatives/aare_gorge_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/aare_gorge_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/aare_gorge_p4/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#brienzer_rothorn": [
    {
      "src": "derivatives/brienzer_rothorn_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/brienzer_rothorn_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/brienzer_rothorn_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#hardergrat_trail": [
    {
      "src": "derivatives/hardergrat_trail_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/hardergrat_trail_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/hardergrat_trail_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/hardergrat_trail_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/hardergrat_trail_p4/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/hardergrat_trail_p5/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#tannhorn": [
    {
      "src": "derivatives/tannhorn_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/tannhorn_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/tannhorn_p2/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/tannhorn_p3/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#augstmatthorn": [
    {
      "src": "derivatives/augstmatthorn_p0/w1800.webp",
      "credit": "Cédric Streit"
    },
    {
      "src": "derivatives/augstmatthorn_p1/w1800.webp",
      "credit": "Gian Porsius"
    },
    {
      "src": "derivatives/augstmatthorn_p2/w1800.webp",
      "credit": "Jana Leu"
    },
    {
      "src": "derivatives/augstmatthorn_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/augstmatthorn_p4/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#lake_lucerne": [
    {
      "src": "derivatives/lake_lucerne_p0/w1800.webp",
      "credit": "Daniel Cox"
    },
    {
      "src": "derivatives/lake_lucerne_p1/w1800.webp",
      "credit": "Marco Steiger"
    },
    {
      "src": "derivatives/lake_lucerne_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#fronalpstock": [
    {
      "src": "derivatives/fronalpstock_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fronalpstock_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/fronalpstock_p2/w1800.webp",
      "credit": "@oliwear.j"
    }
  ],
  "central#fulberg": [
    {
      "src": "derivatives/fulberg_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p1/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p2/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p4/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p5/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p6/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#iffigfalle": [
    {
      "src": "derivatives/iffigfalle_p0/w1800.webp",
      "credit": "@fototaeschli"
    },
    {
      "src": "derivatives/iffigfalle_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/iffigfalle_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#schrattenfluh": [
    {
      "src": "derivatives/schrattenfluh_p0/w1800.webp",
      "credit": "Cyprien Da Silva"
    },
    {
      "src": "derivatives/schrattenfluh_p1/w1800.webp",
      "credit": "xxx"
    },
    {
      "src": "derivatives/schrattenfluh_p2/w1800.webp",
      "credit": "xxx"
    },
    {
      "src": "derivatives/schrattenfluh_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schrattenfluh_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schrattenfluh_p5/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schrattenfluh_p6/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schrattenfluh_p7/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schrattenfluh_p8/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schrattenfluh_p9/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#heftihutte": [
    {
      "src": "derivatives/heftihutte_p0/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/heftihutte_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/heftihutte_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/heftihutte_p3/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#bachalpsee": [
    {
      "src": "derivatives/bachalpsee_p0/w1800.webp",
      "credit": "Rowell Heria"
    },
    {
      "src": "derivatives/bachalpsee_p1/w1800.webp",
      "credit": "Valerie Calabro"
    },
    {
      "src": "derivatives/bachalpsee_p2/w1800.webp",
      "credit": "Ansgar Scheffold"
    }
  ],
  "central#grindelwald": [
    {
      "src": "derivatives/grindelwald_p0/w1800.webp",
      "credit": "Anna Hu"
    },
    {
      "src": "derivatives/grindelwald_p1/w1800.webp",
      "credit": "Ruth Georgiev"
    },
    {
      "src": "derivatives/grindelwald_p2/w1800.webp",
      "credit": "Lauren Dietz"
    },
    {
      "src": "derivatives/grindelwald_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#iseltwald": [
    {
      "src": "derivatives/iseltwald_p0/w1800.webp",
      "credit": "Yasintha Perera"
    },
    {
      "src": "derivatives/iseltwald_p1/w1800.webp",
      "credit": "Yasintha Perera"
    },
    {
      "src": "derivatives/iseltwald_p2/w1800.webp",
      "credit": "Omid Visuals"
    },
    {
      "src": "derivatives/iseltwald_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#viewpoint_beatenberg": [
    {
      "src": "derivatives/viewpoint_beatenberg_p0/w1800.webp",
      "credit": "Jairph"
    },
    {
      "src": "derivatives/viewpoint_beatenberg_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#oeschinensee": [
    {
      "src": "derivatives/oeschinensee_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/oeschinensee_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/oeschinensee_p2/w1800.webp",
      "credit": "Peter Elijah"
    },
    {
      "src": "derivatives/oeschinensee_p3/w1800.webp",
      "credit": "Dennis H."
    },
    {
      "src": "derivatives/oeschinensee_p4/w1800.webp",
      "credit": "Pascal Debrunner"
    },
    {
      "src": "derivatives/oeschinensee_p5/w1800.webp",
      "credit": "Manca Cadez"
    },
    {
      "src": "derivatives/oeschinensee_p6/w1800.webp",
      "credit": "Gabriel Cirelli"
    },
    {
      "src": "derivatives/oeschinensee_p7/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/oeschinensee_p8/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#piz_gloria": [
    {
      "src": "derivatives/piz_gloria_p0/w1800.webp",
      "credit": "Anthony Gomez"
    },
    {
      "src": "derivatives/piz_gloria_p1/w1800.webp",
      "credit": "Dimitri Karastelev"
    },
    {
      "src": "derivatives/piz_gloria_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/piz_gloria_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "central#lauterbrunnen": [
    {
      "src": "derivatives/lauterbrunnen_p0/w1800.webp",
      "credit": "Omid Visuals"
    },
    {
      "src": "derivatives/lauterbrunnen_p1/w1800.webp",
      "credit": "Maximilian Jaenicke"
    },
    {
      "src": "derivatives/lauterbrunnen_p2/w1800.webp",
      "credit": "Omid Visuals"
    },
    {
      "src": "derivatives/lauterbrunnen_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/lauterbrunnen_p4/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#riffelsee": [
    {
      "src": "derivatives/riffelsee_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/riffelsee_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/riffelsee_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/riffelsee_p3/w1800.webp",
      "credit": "Lukáš Konvica"
    },
    {
      "src": "derivatives/riffelsee_p4/w1800.webp",
      "credit": "Ilia Bronskyi"
    },
    {
      "src": "derivatives/riffelsee_p5/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/riffelsee_p6/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/riffelsee_p7/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/riffelsee_p8/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/riffelsee_p9/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "valais#zermatt_village": [
    {
      "src": "derivatives/zermatt_village_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/zermatt_village_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/zermatt_village_p2/w1800.webp",
      "credit": "Daniel Cox"
    }
  ],
  "valais#riffelalp": [
    {
      "src": "derivatives/riffelalp_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/riffelalp_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/riffelalp_p2/w1800.webp",
      "credit": "@oliwear.j"
    }
  ],
  "valais#gorner_glacier": [
    {
      "src": "derivatives/gorner_glacier_p0/w1800.webp",
      "credit": "Thomas Lipke"
    },
    {
      "src": "derivatives/gorner_glacier_p1/w1800.webp",
      "credit": "Agata Bres"
    },
    {
      "src": "derivatives/gorner_glacier_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#zermatt_huts": [
    {
      "src": "derivatives/zermatt_huts_p0/w1800.webp",
      "credit": null
    },
    {
      "src": "derivatives/zermatt_huts_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#aletsch_glacier": [
    {
      "src": "derivatives/aletsch_glacier_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/aletsch_glacier_p1/w1800.webp",
      "credit": "Ernst Bürki"
    },
    {
      "src": "derivatives/aletsch_glacier_p2/w1800.webp",
      "credit": "Andrea Russu"
    },
    {
      "src": "derivatives/aletsch_glacier_p3/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/aletsch_glacier_p4/w1800.webp",
      "credit": "Louise Pipet"
    },
    {
      "src": "derivatives/aletsch_glacier_p5/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#arolla_ice_cave": [
    {
      "src": "derivatives/arolla_ice_cave_p0/w1800.webp",
      "credit": "@glacionaut"
    },
    {
      "src": "derivatives/arolla_ice_cave_p1/w1800.webp",
      "credit": "@isleifureli"
    },
    {
      "src": "derivatives/arolla_ice_cave_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#cabane_becs_de_bosson": [
    {
      "src": "derivatives/cabane_becs_de_bosson_p0/w1800.webp",
      "credit": "@damien.bozzini"
    },
    {
      "src": "derivatives/cabane_becs_de_bosson_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/cabane_becs_de_bosson_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#moiry_glacier": [
    {
      "src": "derivatives/moiry_glacier_p0/w1800.webp",
      "credit": "@mofitrando"
    },
    {
      "src": "derivatives/moiry_glacier_p1/w1800.webp",
      "credit": "@steffi.outbound"
    },
    {
      "src": "derivatives/moiry_glacier_p2/w1800.webp",
      "credit": "@steffi.outbound"
    },
    {
      "src": "derivatives/moiry_glacier_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/moiry_glacier_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/moiry_glacier_p5/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/moiry_glacier_p6/w1800.webp",
      "credit": "@steffi.outbound"
    }
  ],
  "valais#the_ice_cave": [
    {
      "src": "derivatives/the_ice_cave_p0/w1800.webp",
      "credit": "@isleifureli"
    },
    {
      "src": "derivatives/the_ice_cave_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/the_ice_cave_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/the_ice_cave_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/the_ice_cave_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/the_ice_cave_p5/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/the_ice_cave_p6/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/the_ice_cave_p7/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/the_ice_cave_p8/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#ferpecle_glacier": [
    {
      "src": "derivatives/ferpecle_glacier_p0/w1800.webp",
      "credit": "@mofitrando"
    },
    {
      "src": "derivatives/ferpecle_glacier_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#ferpecle_river": [
    {
      "src": "derivatives/ferpecle_river_p0/w1800.webp",
      "credit": "@oliwvair"
    },
    {
      "src": "derivatives/ferpecle_river_p1/w1800.webp",
      "credit": "@oliwvair"
    },
    {
      "src": "derivatives/ferpecle_river_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#spielboden": [
    {
      "src": "derivatives/spielboden_p0/w1800.webp",
      "credit": "@babooshka_pl"
    },
    {
      "src": "derivatives/spielboden_p1/w1800.webp",
      "credit": "Jurjen Vos"
    }
  ],
  "valais#goms_bridge": [
    {
      "src": "derivatives/goms_bridge_p0/w1800.webp",
      "credit": "Adrien Olichon"
    },
    {
      "src": "derivatives/goms_bridge_p1/w1800.webp",
      "credit": "Adrien Olichon"
    }
  ],
  "valais#randa_bridge": [
    {
      "src": "derivatives/randa_bridge_p0/w1800.webp",
      "credit": "@tricking.adventures"
    },
    {
      "src": "derivatives/randa_bridge_p1/w1800.webp",
      "credit": "@tricking.adventures"
    }
  ],
  "valais#saas_fee_glacier": [
    {
      "src": "derivatives/saas_fee_glacier_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/saas_fee_glacier_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#lac_de_derborence": [
    {
      "src": "derivatives/lac_de_derborence_p0/w1800.webp",
      "credit": null
    },
    {
      "src": "derivatives/lac_de_derborence_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#la_fouly": [
    {
      "src": "derivatives/la_fouly_p0/w1800.webp",
      "credit": "@explore_a_perte_de_vue"
    },
    {
      "src": "derivatives/la_fouly_p1/w1800.webp",
      "credit": "@explore_a_perte_de_vue"
    },
    {
      "src": "derivatives/la_fouly_p2/w1800.webp",
      "credit": "@explore_a_perte_de_vue"
    },
    {
      "src": "derivatives/la_fouly_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/la_fouly_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/la_fouly_p5/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/la_fouly_p6/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#sanetschpass": [
    {
      "src": "derivatives/sanetschpass_p0/w1800.webp",
      "credit": "@berniejustlooksaround"
    },
    {
      "src": "derivatives/sanetschpass_p1/w1800.webp",
      "credit": "valaiswallis"
    },
    {
      "src": "derivatives/sanetschpass_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#gorges_du_durnand": [
    {
      "src": "derivatives/gorges_du_durnand_p0/w1800.webp",
      "credit": "@travelwithmaria_"
    },
    {
      "src": "derivatives/gorges_du_durnand_p1/w1800.webp",
      "credit": "ivansoko_"
    },
    {
      "src": "derivatives/gorges_du_durnand_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/gorges_du_durnand_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#gorges_du_dailley": [
    {
      "src": "derivatives/gorges_du_dailley_p0/w1800.webp",
      "credit": "@hebergements_les_rochers"
    },
    {
      "src": "derivatives/gorges_du_dailley_p1/w1800.webp",
      "credit": "@hebergements_les_rochers"
    },
    {
      "src": "derivatives/gorges_du_dailley_p2/w1800.webp",
      "credit": "vallee_du_trient"
    },
    {
      "src": "derivatives/gorges_du_dailley_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#nax_via_ferrata": [
    {
      "src": "derivatives/nax_via_ferrata_p0/w1800.webp",
      "credit": "@tanguy.espejo"
    },
    {
      "src": "derivatives/nax_via_ferrata_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/nax_via_ferrata_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#crans_montana": [
    {
      "src": "derivatives/crans_montana_p0/w1800.webp",
      "credit": "Artiom Vallat"
    },
    {
      "src": "derivatives/crans_montana_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#tseuzier_lake": [
    {
      "src": "derivatives/tseuzier_lake_p0/w1800.webp",
      "credit": "@benwe_"
    },
    {
      "src": "derivatives/tseuzier_lake_p1/w1800.webp",
      "credit": "@benwe_"
    },
    {
      "src": "derivatives/tseuzier_lake_p2/w1800.webp",
      "credit": "@steffi_inswiss"
    },
    {
      "src": "derivatives/tseuzier_lake_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#salanfe_lake": [
    {
      "src": "derivatives/salanfe_lake_p0/w1800.webp",
      "credit": "@guidos.tours"
    },
    {
      "src": "derivatives/salanfe_lake_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#la_tzoumaz": [
    {
      "src": "derivatives/la_tzoumaz_p0/w1800.webp",
      "credit": null
    },
    {
      "src": "derivatives/la_tzoumaz_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "fribourg#gastlosen": [
    {
      "src": "derivatives/gastlosen_p0/w1800.webp",
      "credit": "frdm"
    },
    {
      "src": "derivatives/gastlosen_p1/w1800.webp",
      "credit": "Xavier von Erlach"
    },
    {
      "src": "derivatives/gastlosen_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "fribourg#ritzli_alp": [
    {
      "src": "derivatives/ritzli_alp_p0/w1800.webp",
      "credit": "@ritzli"
    },
    {
      "src": "derivatives/ritzli_alp_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "fribourg#dent_de_broc": [
    {
      "src": "derivatives/dent_de_broc_p0/w1800.webp",
      "credit": "@danielborloz"
    },
    {
      "src": "derivatives/dent_de_broc_p1/w1800.webp",
      "credit": "ingenieuse.ch"
    },
    {
      "src": "derivatives/dent_de_broc_p2/w1800.webp",
      "credit": "@sherpa__tenzin"
    },
    {
      "src": "derivatives/dent_de_broc_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "fribourg#schwarzsee": [
    {
      "src": "derivatives/schwarzsee_p0/w1800.webp",
      "credit": "@noberson"
    },
    {
      "src": "derivatives/schwarzsee_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schwarzsee_p2/w1800.webp",
      "credit": "@spornitho"
    },
    {
      "src": "derivatives/schwarzsee_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "fribourg#dent_de_lys": [
    {
      "src": "derivatives/dent_de_lys_p0/w1800.webp",
      "credit": "@patrick.janser"
    },
    {
      "src": "derivatives/dent_de_lys_p1/w1800.webp",
      "credit": "@patrick.janser"
    },
    {
      "src": "derivatives/dent_de_lys_p2/w1800.webp",
      "credit": "lj.delos"
    },
    {
      "src": "derivatives/dent_de_lys_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "fribourg#moleson": [
    {
      "src": "derivatives/moleson_p0/w1800.webp",
      "credit": "@markhebertphoto"
    },
    {
      "src": "derivatives/moleson_p1/w1800.webp",
      "credit": "moleson_official"
    },
    {
      "src": "derivatives/moleson_p2/w1800.webp",
      "credit": "myswitzerlandru"
    },
    {
      "src": "derivatives/moleson_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "fribourg#teysachaux": [
    {
      "src": "derivatives/teysachaux_p0/w1800.webp",
      "credit": "@o_fargnoli"
    },
    {
      "src": "derivatives/teysachaux_p1/w1800.webp",
      "credit": "fribourgch"
    },
    {
      "src": "derivatives/teysachaux_p2/w1800.webp",
      "credit": "fribourgch"
    },
    {
      "src": "derivatives/teysachaux_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#cap_au_moine": [
    {
      "src": "derivatives/cap_au_moine_p0/w1800.webp",
      "credit": "@danslafosse.medias"
    },
    {
      "src": "derivatives/cap_au_moine_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/cap_au_moine_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/cap_au_moine_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/cap_au_moine_p4/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#dent_de_jaman": [
    {
      "src": "derivatives/dent_de_jaman_p0/w1800.webp",
      "credit": "Xavier von Erlach"
    },
    {
      "src": "derivatives/dent_de_jaman_p1/w1800.webp",
      "credit": "@guidos.tours"
    },
    {
      "src": "derivatives/dent_de_jaman_p2/w1800.webp",
      "credit": "xavier.paillard"
    },
    {
      "src": "derivatives/dent_de_jaman_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#gorges_du_chauderon": [
    {
      "src": "derivatives/gorges_du_chauderon_p0/w1800.webp",
      "credit": null
    },
    {
      "src": "derivatives/gorges_du_chauderon_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/gorges_du_chauderon_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#pisse_chevre": [
    {
      "src": "derivatives/pisse_chevre_p0/w1800.webp",
      "credit": "@samsurinwelch"
    },
    {
      "src": "derivatives/pisse_chevre_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#route_de_morcles": [
    {
      "src": "derivatives/route_de_morcles_p0/w1800.webp",
      "credit": null
    },
    {
      "src": "derivatives/route_de_morcles_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#creux_du_van": [
    {
      "src": "derivatives/creux_du_van_p0/w1800.webp",
      "credit": "Daniel R."
    },
    {
      "src": "derivatives/creux_du_van_p1/w1800.webp",
      "credit": "visitsuisse"
    },
    {
      "src": "derivatives/creux_du_van_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/creux_du_van_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/creux_du_van_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/creux_du_van_p5/w1800.webp",
      "credit": "@jura3lacs"
    },
    {
      "src": "derivatives/creux_du_van_p6/w1800.webp",
      "credit": "@jura3lacs"
    },
    {
      "src": "derivatives/creux_du_van_p7/w1800.webp",
      "credit": "@claude_gurzeler"
    },
    {
      "src": "derivatives/creux_du_van_p8/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#tine_de_conflens": [
    {
      "src": "derivatives/tine_de_conflens_p0/w1800.webp",
      "credit": "@christofs70"
    },
    {
      "src": "derivatives/tine_de_conflens_p1/w1800.webp",
      "credit": "andybuettiker"
    }
  ],
  "western#lac_de_taney": [
    {
      "src": "derivatives/lac_de_taney_p0/w1800.webp",
      "credit": "@alpenliebe_official"
    },
    {
      "src": "derivatives/lac_de_taney_p1/w1800.webp",
      "credit": "@tcheucestbeau"
    },
    {
      "src": "derivatives/lac_de_taney_p2/w1800.webp",
      "credit": "@tcheucestbeau"
    },
    {
      "src": "derivatives/lac_de_taney_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#grammont": [
    {
      "src": "derivatives/grammont_p0/w1800.webp",
      "credit": "@andresduranco"
    },
    {
      "src": "derivatives/grammont_p1/w1800.webp",
      "credit": "bagpictures"
    },
    {
      "src": "derivatives/grammont_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#st_prex": [
    {
      "src": "derivatives/st_prex_p0/w1800.webp",
      "credit": "@oliwvair1"
    },
    {
      "src": "derivatives/st_prex_p1/w1800.webp",
      "credit": "@oliwvair"
    },
    {
      "src": "derivatives/st_prex_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#marchairuz": [
    {
      "src": "derivatives/marchairuz_p0/w1800.webp",
      "credit": "@jenniferesseiva"
    },
    {
      "src": "derivatives/marchairuz_p1/w1800.webp",
      "credit": "@jenniferesseiva"
    },
    {
      "src": "derivatives/marchairuz_p2/w1800.webp",
      "credit": "@jenniferesseiva"
    },
    {
      "src": "derivatives/marchairuz_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#geltenschuss": [
    {
      "src": "derivatives/geltenschuss_p0/w1800.webp",
      "credit": "@davidbirri"
    },
    {
      "src": "derivatives/geltenschuss_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#lavaux_vineyards": [
    {
      "src": "derivatives/lavaux_vineyards_p0/w1800.webp",
      "credit": "Razvan Sassu"
    },
    {
      "src": "derivatives/lavaux_vineyards_p1/w1800.webp",
      "credit": "patrykbieganski"
    }
  ],
  "western#etang_de_la_gruere": [
    {
      "src": "derivatives/etang_de_la_gruere_p0/w1800.webp",
      "credit": "@claude_gurzeler"
    },
    {
      "src": "derivatives/etang_de_la_gruere_p1/w1800.webp",
      "credit": "macoooy25"
    },
    {
      "src": "derivatives/etang_de_la_gruere_p2/w1800.webp",
      "credit": "@jura3lacs"
    },
    {
      "src": "derivatives/etang_de_la_gruere_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "western#le_doubs": [
    {
      "src": "derivatives/le_doubs_p0/w1800.webp",
      "credit": "@jura3lacs"
    },
    {
      "src": "derivatives/le_doubs_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#schafler": [
    {
      "src": "derivatives/schafler_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/schafler_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schafler_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/schafler_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/schafler_p4/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/schafler_p5/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#seealpsee": [
    {
      "src": "derivatives/seealpsee_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/seealpsee_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/seealpsee_p2/w1800.webp",
      "credit": "Ilia Bronskyi"
    },
    {
      "src": "derivatives/seealpsee_p3/w1800.webp",
      "credit": "Simon Spring"
    },
    {
      "src": "derivatives/seealpsee_p4/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/seealpsee_p5/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/seealpsee_p6/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#ascher": [
    {
      "src": "derivatives/ascher_p0/w1800.webp",
      "credit": "Ilia Bronskyi"
    },
    {
      "src": "derivatives/ascher_p1/w1800.webp",
      "credit": "Niklas Tidbury"
    },
    {
      "src": "derivatives/ascher_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#saxer_lucke": [
    {
      "src": "derivatives/saxer_lucke_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/saxer_lucke_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/saxer_lucke_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/saxer_lucke_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/saxer_lucke_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/saxer_lucke_p5/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/saxer_lucke_p6/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#limmernsee": [
    {
      "src": "derivatives/limmernsee_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/limmernsee_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/limmernsee_p2/w1800.webp",
      "credit": "Minsu B."
    },
    {
      "src": "derivatives/limmernsee_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/limmernsee_p4/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/limmernsee_p5/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/limmernsee_p6/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#muttseehutte": [
    {
      "src": "derivatives/muttseehutte_p0/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/muttseehutte_p1/w1800.webp",
      "credit": "@jvm_photography"
    },
    {
      "src": "derivatives/muttseehutte_p2/w1800.webp",
      "credit": "@jvm_photography"
    },
    {
      "src": "derivatives/muttseehutte_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/muttseehutte_p4/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#berschnerfall": [
    {
      "src": "derivatives/berschnerfall_p0/w1800.webp",
      "credit": "@sabrina.binkert"
    },
    {
      "src": "derivatives/berschnerfall_p1/w1800.webp",
      "credit": "@sabrina.binkert"
    },
    {
      "src": "derivatives/berschnerfall_p2/w1800.webp",
      "credit": "marcelsiebert_"
    },
    {
      "src": "derivatives/berschnerfall_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/berschnerfall_p4/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#klausenpass": [
    {
      "src": "derivatives/klausenpass_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/klausenpass_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/klausenpass_p2/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/klausenpass_p3/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#barglistuber": [
    {
      "src": "derivatives/barglistuber_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/barglistuber_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#urnerboden": [
    {
      "src": "derivatives/urnerboden_p0/w1800.webp",
      "credit": "@1000schweizerorte"
    },
    {
      "src": "derivatives/urnerboden_p1/w1800.webp",
      "credit": "sandro_bedin_landscapes"
    },
    {
      "src": "derivatives/urnerboden_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#ice_lake_griesslisee": [
    {
      "src": "derivatives/ice_lake_griesslisee_p0/w1800.webp",
      "credit": "@aventouro"
    },
    {
      "src": "derivatives/ice_lake_griesslisee_p1/w1800.webp",
      "credit": "glarnerland.ch"
    },
    {
      "src": "derivatives/ice_lake_griesslisee_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/ice_lake_griesslisee_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#gigerwaldsee": [
    {
      "src": "derivatives/gigerwaldsee_p0/w1800.webp",
      "credit": "@aventouro"
    },
    {
      "src": "derivatives/gigerwaldsee_p1/w1800.webp",
      "credit": "patricialang_photography"
    },
    {
      "src": "derivatives/gigerwaldsee_p2/w1800.webp",
      "credit": "patricialang_photography"
    },
    {
      "src": "derivatives/gigerwaldsee_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#caumasee": [
    {
      "src": "derivatives/caumasee_p0/w1800.webp",
      "credit": "@mattiaantonelliofficial"
    },
    {
      "src": "derivatives/caumasee_p1/w1800.webp",
      "credit": "@mattiaantonelliofficial"
    },
    {
      "src": "derivatives/caumasee_p2/w1800.webp",
      "credit": "flo.jhngtn"
    },
    {
      "src": "derivatives/caumasee_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#ruinaulta": [
    {
      "src": "derivatives/ruinaulta_p0/w1800.webp",
      "credit": "Jan Huber"
    },
    {
      "src": "derivatives/ruinaulta_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#crestasee": [
    {
      "src": "derivatives/crestasee_p0/w1800.webp",
      "credit": "@signaphoto"
    },
    {
      "src": "derivatives/crestasee_p1/w1800.webp",
      "credit": "flo.jhngtn"
    },
    {
      "src": "derivatives/crestasee_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/crestasee_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#klontalersee": [
    {
      "src": "derivatives/klontalersee_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/klontalersee_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/klontalersee_p2/w1800.webp",
      "credit": "Gabriel Herter"
    },
    {
      "src": "derivatives/klontalersee_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/klontalersee_p4/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#stoos_kapelle": [
    {
      "src": "derivatives/stoos_kapelle_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/stoos_kapelle_p1/w1800.webp",
      "credit": "Max Bürgi"
    },
    {
      "src": "derivatives/stoos_kapelle_p2/w1800.webp",
      "credit": "Claudio Schwarz"
    },
    {
      "src": "derivatives/stoos_kapelle_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/stoos_kapelle_p4/w1800.webp",
      "credit": "@yannick_sutter"
    },
    {
      "src": "derivatives/stoos_kapelle_p5/w1800.webp",
      "credit": "@oliwear.j"
    }
  ],
  "eastern#pizol": [
    {
      "src": "derivatives/pizol_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/pizol_p1/w1800.webp",
      "credit": "Boris Baldinger"
    },
    {
      "src": "derivatives/pizol_p2/w1800.webp",
      "credit": "Vasyl Dizhak"
    },
    {
      "src": "derivatives/pizol_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/pizol_p4/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#joriseen": [
    {
      "src": "derivatives/joriseen_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/joriseen_p1/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/joriseen_p2/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/joriseen_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/joriseen_p4/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/joriseen_p5/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "eastern#falensee": [
    {
      "src": "derivatives/falensee_p0/w1800.webp",
      "credit": "Bö Benkö"
    },
    {
      "src": "derivatives/falensee_p1/w1800.webp",
      "credit": "Chris Henry"
    },
    {
      "src": "derivatives/falensee_p2/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/falensee_p3/w1800.webp",
      "credit": "Ilia Bronskyi"
    }
  ],
  "eastern#morteratsch_glacier": [
    {
      "src": "derivatives/morteratsch_glacier_p0/w1800.webp",
      "credit": "@samir.sparks"
    },
    {
      "src": "derivatives/morteratsch_glacier_p1/w1800.webp",
      "credit": "graubuenden"
    },
    {
      "src": "derivatives/morteratsch_glacier_p2/w1800.webp",
      "credit": "jonglr"
    },
    {
      "src": "derivatives/morteratsch_glacier_p3/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/morteratsch_glacier_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/morteratsch_glacier_p5/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#bovalhutte": [
    {
      "src": "derivatives/bovalhutte_p0/w1800.webp",
      "credit": "@dario_monn"
    },
    {
      "src": "derivatives/bovalhutte_p1/w1800.webp",
      "credit": "mrcgbr"
    },
    {
      "src": "derivatives/bovalhutte_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#spitzmeilenhutte": [
    {
      "src": "derivatives/spitzmeilenhutte_p0/w1800.webp",
      "credit": "@kurtschwendener"
    },
    {
      "src": "derivatives/spitzmeilenhutte_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "ticino#cascata_la_froda": [
    {
      "src": "derivatives/cascata_la_froda_p0/w1800.webp",
      "credit": "@kalapascal"
    },
    {
      "src": "derivatives/cascata_la_froda_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "ticino#ponte_dei_salti": [
    {
      "src": "derivatives/ponte_dei_salti_p0/w1800.webp",
      "credit": "Claudio Schwarz"
    },
    {
      "src": "derivatives/ponte_dei_salti_p1/w1800.webp",
      "credit": "Tom Moser"
    },
    {
      "src": "derivatives/ponte_dei_salti_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "ticino#valle_verzasca": [
    {
      "src": "derivatives/valle_verzasca_p0/w1800.webp",
      "credit": "Artiom Vallat"
    },
    {
      "src": "derivatives/valle_verzasca_p1/w1800.webp",
      "credit": "Nadine Marfurt"
    },
    {
      "src": "derivatives/valle_verzasca_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/valle_verzasca_p3/w1800.webp",
      "credit": "@noelbell8"
    },
    {
      "src": "derivatives/valle_verzasca_p4/w1800.webp",
      "credit": "bike2boat.eu"
    },
    {
      "src": "derivatives/valle_verzasca_p5/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "ticino#lavertezzo": [
    {
      "src": "derivatives/lavertezzo_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/lavertezzo_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "ticino#ponte_brolla": [
    {
      "src": "derivatives/ponte_brolla_p0/w1800.webp",
      "credit": "@locarnesetv"
    },
    {
      "src": "derivatives/ponte_brolla_p1/w1800.webp",
      "credit": "@locarnesetv"
    },
    {
      "src": "derivatives/ponte_brolla_p2/w1800.webp",
      "credit": "@locarnesetv"
    }
  ],
  "beyond#mer_de_glace": [
    {
      "src": "derivatives/mer_de_glace_p0/w1800.webp",
      "credit": "Simon Fitall"
    },
    {
      "src": "derivatives/mer_de_glace_p1/w1800.webp",
      "credit": "lerefugedusapi"
    },
    {
      "src": "derivatives/mer_de_glace_p2/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/mer_de_glace_p3/w1800.webp",
      "credit": "Martin Masson"
    },
    {
      "src": "derivatives/mer_de_glace_p4/w1800.webp",
      "credit": "Ricardo Frantz"
    },
    {
      "src": "derivatives/mer_de_glace_p5/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "beyond#les_drus": [
    {
      "src": "derivatives/les_drus_p0/w1800.webp",
      "credit": "@olivieredme"
    },
    {
      "src": "derivatives/les_drus_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/les_drus_p2/w1800.webp",
      "credit": "@robingaillotdrevon"
    },
    {
      "src": "derivatives/les_drus_p3/w1800.webp",
      "credit": "atmb_vivreenhautesavoie"
    },
    {
      "src": "derivatives/les_drus_p4/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/les_drus_p5/w1800.webp",
      "credit": "xxx"
    }
  ],
  "beyond#aiguille_du_grepon": [
    {
      "src": "derivatives/aiguille_du_grepon_p0/w1800.webp",
      "credit": "@himalalts"
    },
    {
      "src": "derivatives/aiguille_du_grepon_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "beyond#les_cheserys": [
    {
      "src": "derivatives/les_cheserys_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/les_cheserys_p1/w1800.webp",
      "credit": "zimydakid"
    },
    {
      "src": "derivatives/les_cheserys_p2/w1800.webp",
      "credit": "xxx"
    },
    {
      "src": "derivatives/les_cheserys_p3/w1800.webp",
      "credit": "@taufiqsaidi_"
    },
    {
      "src": "derivatives/les_cheserys_p4/w1800.webp",
      "credit": "@taufiqsaidi_"
    },
    {
      "src": "derivatives/les_cheserys_p5/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "beyond#camping_in_cheserys": [
    {
      "src": "derivatives/camping_in_cheserys_p0/w1800.webp",
      "credit": "@damien_paysages_et_sport"
    },
    {
      "src": "derivatives/camping_in_cheserys_p1/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/camping_in_cheserys_p2/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "beyond#mont_blanc": [
    {
      "src": "derivatives/mont_blanc_p0/w1800.webp",
      "credit": "Andrea Caramello"
    },
    {
      "src": "derivatives/mont_blanc_p1/w1800.webp",
      "credit": "Nicolas Weldingh"
    },
    {
      "src": "derivatives/mont_blanc_p2/w1800.webp",
      "credit": "jimmybiggey"
    },
    {
      "src": "derivatives/mont_blanc_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "beyond#glacier_des_bossons": [
    {
      "src": "derivatives/glacier_des_bossons_p0/w1800.webp",
      "credit": "@jules_s_photography"
    },
    {
      "src": "derivatives/glacier_des_bossons_p1/w1800.webp",
      "credit": "romainverdure"
    },
    {
      "src": "derivatives/glacier_des_bossons_p2/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "beyond#pic_de_jallouvre": [
    {
      "src": "derivatives/pic_de_jallouvre_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/pic_de_jallouvre_p1/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/pic_de_jallouvre_p2/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/pic_de_jallouvre_p3/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/pic_de_jallouvre_p4/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/pic_de_jallouvre_p5/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "beyond#dent_doche": [
    {
      "src": "derivatives/dent_doche_p0/w1800.webp",
      "credit": "@syma_photography"
    },
    {
      "src": "derivatives/dent_doche_p1/w1800.webp",
      "credit": "@syma_photography"
    },
    {
      "src": "derivatives/dent_doche_p2/w1800.webp",
      "credit": "@syma_photography"
    },
    {
      "src": "derivatives/dent_doche_p3/w1800.webp",
      "credit": "@syma_photography"
    }
  ],
  "central#brisen": [
    {
      "src": "derivatives/brisen_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/brisen_p1/w1800.webp",
      "credit": "@andeast"
    }
  ],
  "central#engstlensee": [
    {
      "src": "derivatives/engstlensee_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/engstlensee_p1/w1800.webp",
      "credit": "@juiz.mein.nidwalden"
    },
    {
      "src": "derivatives/engstlensee_p2/w1800.webp",
      "credit": "@visitswitzerland"
    },
    {
      "src": "derivatives/engstlensee_p3/w1800.webp",
      "credit": "@obwaldentourismus"
    }
  ],
  "eastern#maloja_pass": [
    {
      "src": "derivatives/maloja_pass_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/maloja_pass_p1/w1800.webp",
      "credit": "Johannes Hofmann"
    },
    {
      "src": "derivatives/maloja_pass_p2/w1800.webp",
      "credit": "@me.and.eloise"
    }
  ],
  "ticino#ponte_tibetano": [
    {
      "src": "derivatives/ponte_tibetano_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/ponte_tibetano_p1/w1800.webp",
      "credit": "@alnai1mi"
    },
    {
      "src": "derivatives/ponte_tibetano_p2/w1800.webp",
      "credit": "@alnai1mi"
    },
    {
      "src": "derivatives/ponte_tibetano_p3/w1800.webp",
      "credit": "@ludovicpizzera"
    }
  ],
  "valais#zinal_glacier": [
    {
      "src": "derivatives/zinal_glacier_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/zinal_glacier_p1/w1800.webp",
      "credit": "@oliwear.j"
    }
  ],
  "eastern#grappelensee": [
    {
      "src": "derivatives/grappelensee_p0/w1800.webp",
      "credit": "@oliwear.j"
    },
    {
      "src": "derivatives/grappelensee_p1/w1800.webp",
      "credit": "Ivan Louis"
    },
    {
      "src": "derivatives/grappelensee_p2/w1800.webp",
      "credit": "Janosch Diggelmann"
    }
  ],
  "central#mount_pilatus": [
    {
      "src": "derivatives/mount_pilatus_p0/w1800.webp",
      "credit": "Emanuel Kionke"
    },
    {
      "src": "derivatives/mount_pilatus_p1/w1800.webp",
      "credit": "Razvan Sassu"
    },
    {
      "src": "derivatives/mount_pilatus_p2/w1800.webp",
      "credit": "Emanuel Kionke"
    }
  ],
  "central#wasserfall_finstersee": [
    {
      "src": "derivatives/wasserfall_finstersee_p0/w1800.webp",
      "credit": "@daniel_staub_photo"
    },
    {
      "src": "derivatives/wasserfall_finstersee_p1/w1800.webp",
      "credit": "@michelrohner_fotografie"
    },
    {
      "src": "derivatives/wasserfall_finstersee_p2/w1800.webp",
      "credit": "@fotobolle"
    }
  ],
  "valais#lac_bleu": [
    {
      "src": "derivatives/lac_bleu_p0/w1800.webp",
      "credit": "@annamariastravel"
    },
    {
      "src": "derivatives/lac_bleu_p1/w1800.webp",
      "credit": "@annamariastravel"
    }
  ],
  "eastern#wildsee": [
    {
      "src": "derivatives/wildsee_p0/w1800.webp",
      "credit": "Claudio Schwarz"
    },
    {
      "src": "derivatives/wildsee_p1/w1800.webp",
      "credit": "@upsidenomads"
    },
    {
      "src": "derivatives/wildsee_p2/w1800.webp",
      "credit": "@travel_with_domi"
    }
  ],
  "eastern#julier_pass": [
    {
      "src": "derivatives/julier_pass_p0/w1800.webp",
      "credit": "Sepp Rutz"
    },
    {
      "src": "derivatives/julier_pass_p1/w1800.webp",
      "credit": "@conquerthecols"
    },
    {
      "src": "derivatives/julier_pass_p2/w1800.webp",
      "credit": "@pm.focus"
    },
    {
      "src": "derivatives/julier_pass_p3/w1800.webp",
      "credit": "@pm.focus"
    }
  ],
  "beyond#refuge_du_lac_blanc": [
    {
      "src": "derivatives/refuge_du_lac_blanc_p0/w1800.webp",
      "credit": "@doytcheva"
    },
    {
      "src": "derivatives/refuge_du_lac_blanc_p1/w1800.webp",
      "credit": "@max.belbeoch"
    },
    {
      "src": "derivatives/refuge_du_lac_blanc_p2/w1800.webp",
      "credit": "@janameerman"
    }
  ],
  "eastern#engadin_autumn": [
    {
      "src": "derivatives/engadin_autumn_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/engadin_autumn_p1/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/engadin_autumn_p2/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/engadin_autumn_p3/w1800.webp",
      "credit": "@leon.helg"
    }
  ]
};
