// Auto-generated by scripts/build-spot-images.mjs.
// Maps a spot key (`<chapter_id>#<anchor>`) to its full photo gallery.
// Index 0 is the primary photo (matches the chapter card's <img>); extras
// come from filename siblings and slide-spread gallery cards. Spots with
// only one photo are NOT listed -- the carousel UI checks for the key
// before activating, so single-photo spots fall back to the static <img>.
window.HB_SPOT_IMAGES = {
  "central#fulberg": [
    {
      "src": "derivatives/central_fulberg_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "fulberg.jpg",
      "credit": "@leon.helg"
    },
    {
      "src": "fulberg2.jpg",
      "credit": "@leon.helg"
    }
  ]
};
