// Auto-generated by scripts/build-spot-images.mjs.
// Maps a spot key (`<chapter_id>#<anchor>`) to its full photo gallery.
// Index 0 is the primary photo (matches the chapter card's <img>); extras
// follow. Spots with only one photo are NOT listed — the carousel UI
// checks for the key before activating, so single-photo spots fall back
// to the static <img>.
window.HB_SPOT_IMAGES = {
  "central#rosenlaui": [
    {
      "src": "derivatives/rosenlaui_p0/w1800.webp",
      "credit": "Simon Spring"
    },
    {
      "src": "derivatives/rosenlaui_p1/w1800.webp",
      "credit": "@katerina.trapp"
    }
  ],
  "central#gelmersee": [
    {
      "src": "derivatives/gelmersee_p0/w1800.webp",
      "credit": "Dario Brönnimann"
    },
    {
      "src": "derivatives/gelmersee_p1/w1800.webp",
      "credit": "Simon Infanger"
    },
    {
      "src": "derivatives/gelmersee_p2/w1800.webp",
      "credit": "Lucas Favre"
    }
  ],
  "central#guttannen_valley": [
    {
      "src": "derivatives/guttannen_valley_p0/w1800.webp",
      "credit": "@shaunaxbst"
    },
    {
      "src": "derivatives/guttannen_valley_p1/w1800.webp",
      "credit": "@shaunaxbst"
    }
  ],
  "central#aare_gorge": [
    {
      "src": "derivatives/aare_gorge_p0/w1800.webp",
      "credit": "Thiva"
    },
    {
      "src": "derivatives/aare_gorge_p1/w1800.webp",
      "credit": "Peter Burdon"
    }
  ],
  "central#lake_lucerne": [
    {
      "src": "derivatives/lake_lucerne_p0/w1800.webp",
      "credit": "Daniel Cox"
    },
    {
      "src": "derivatives/lake_lucerne_p1/w1800.webp",
      "credit": "Marco Steiger"
    }
  ],
  "central#fulberg": [
    {
      "src": "derivatives/fulberg_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p1/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/fulberg_p2/w1800.webp",
      "credit": "@leon.helg"
    }
  ],
  "central#schrattenfluh": [
    {
      "src": "derivatives/schrattenfluh_p0/w1800.webp",
      "credit": "Cyprien Da Silva"
    },
    {
      "src": "derivatives/schrattenfluh_p1/w1800.webp",
      "credit": "xxx"
    },
    {
      "src": "derivatives/schrattenfluh_p2/w1800.webp",
      "credit": "xxx"
    }
  ],
  "central#bachalpsee": [
    {
      "src": "derivatives/bachalpsee_p0/w1800.webp",
      "credit": "Rowell Heria"
    },
    {
      "src": "derivatives/bachalpsee_p1/w1800.webp",
      "credit": "Valerie Calabro"
    },
    {
      "src": "derivatives/bachalpsee_p2/w1800.webp",
      "credit": "Ansgar Scheffold"
    }
  ],
  "central#grindelwald": [
    {
      "src": "derivatives/grindelwald_p0/w1800.webp",
      "credit": "Anna Hu"
    },
    {
      "src": "derivatives/grindelwald_p1/w1800.webp",
      "credit": "Ruth Georgiev"
    },
    {
      "src": "derivatives/grindelwald_p2/w1800.webp",
      "credit": "Lauren Dietz"
    }
  ],
  "central#iseltwald": [
    {
      "src": "derivatives/iseltwald_p0/w1800.webp",
      "credit": "Yasintha Perera"
    },
    {
      "src": "derivatives/iseltwald_p1/w1800.webp",
      "credit": "Yasintha Perera"
    },
    {
      "src": "derivatives/iseltwald_p2/w1800.webp",
      "credit": "Omid Visuals"
    }
  ],
  "central#schilthorn": [
    {
      "src": "derivatives/schilthorn_p0/w1800.webp",
      "credit": "Anthony Gomez"
    },
    {
      "src": "derivatives/schilthorn_p1/w1800.webp",
      "credit": "Dimitri Karastelev"
    }
  ],
  "central#lauterbrunnen": [
    {
      "src": "derivatives/lauterbrunnen_p0/w1800.webp",
      "credit": "Omid Visuals"
    },
    {
      "src": "derivatives/lauterbrunnen_p1/w1800.webp",
      "credit": "Maximilian Jaenicke"
    },
    {
      "src": "derivatives/lauterbrunnen_p2/w1800.webp",
      "credit": "Omid Visuals"
    }
  ],
  "valais#gorner_glacier": [
    {
      "src": "derivatives/gorner_glacier_p0/w1800.webp",
      "credit": "Thomas Lipke"
    },
    {
      "src": "derivatives/gorner_glacier_p1/w1800.webp",
      "credit": "Agata Bres"
    }
  ],
  "valais#aletsch_glacier": [
    {
      "src": "derivatives/aletsch_glacier_p0/w1800.webp",
      "credit": "Louise Pipet"
    },
    {
      "src": "derivatives/aletsch_glacier_p1/w1800.webp",
      "credit": "Ernst Bürki"
    },
    {
      "src": "derivatives/aletsch_glacier_p2/w1800.webp",
      "credit": "Andrea Russu"
    },
    {
      "src": "derivatives/aletsch_glacier_p3/w1800.webp",
      "credit": "@oliwear.j"
    }
  ],
  "valais#arolla_ice_cave": [
    {
      "src": "derivatives/arolla_ice_cave_p0/w1800.webp",
      "credit": "@glacionaut"
    },
    {
      "src": "derivatives/arolla_ice_cave_p1/w1800.webp",
      "credit": "@isleifureli"
    }
  ],
  "valais#cabane_becs_de_bosson": [
    {
      "src": "derivatives/cabane_becs_de_bosson_p0/w1800.webp",
      "credit": "@damien.bozzini"
    },
    {
      "src": "derivatives/cabane_becs_de_bosson_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#moiry_glacier": [
    {
      "src": "derivatives/moiry_glacier_p0/w1800.webp",
      "credit": "@mofitrando"
    },
    {
      "src": "derivatives/moiry_glacier_p1/w1800.webp",
      "credit": "@steffi.outbound"
    },
    {
      "src": "derivatives/moiry_glacier_p2/w1800.webp",
      "credit": "@steffi.outbound"
    }
  ],
  "valais#the_ice_cave": [
    {
      "src": "derivatives/the_ice_cave_p0/w1800.webp",
      "credit": "@isleifureli"
    },
    {
      "src": "derivatives/the_ice_cave_p1/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#ferpecle_river": [
    {
      "src": "derivatives/ferpecle_river_p0/w1800.webp",
      "credit": "@oliwvair"
    },
    {
      "src": "derivatives/ferpecle_river_p1/w1800.webp",
      "credit": "@oliwvair"
    }
  ],
  "valais#spielboden": [
    {
      "src": "derivatives/spielboden_p0/w1800.webp",
      "credit": "@babooshka_pl"
    },
    {
      "src": "derivatives/spielboden_p1/w1800.webp",
      "credit": "Jurjen Vos"
    }
  ],
  "valais#goms_bridge": [
    {
      "src": "derivatives/goms_bridge_p0/w1800.webp",
      "credit": "Adrien Olichon"
    },
    {
      "src": "derivatives/goms_bridge_p1/w1800.webp",
      "credit": "Adrien Olichon"
    }
  ],
  "valais#randa_bridge": [
    {
      "src": "derivatives/randa_bridge_p0/w1800.webp",
      "credit": "@tricking.adventures"
    },
    {
      "src": "derivatives/randa_bridge_p1/w1800.webp",
      "credit": "@tricking.adventures"
    }
  ],
  "valais#la_fouly": [
    {
      "src": "derivatives/la_fouly_p0/w1800.webp",
      "credit": "@explore_a_perte_de_vue"
    },
    {
      "src": "derivatives/la_fouly_p1/w1800.webp",
      "credit": "@explore_a_perte_de_vue"
    },
    {
      "src": "derivatives/la_fouly_p2/w1800.webp",
      "credit": "@explore_a_perte_de_vue"
    },
    {
      "src": "derivatives/la_fouly_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "valais#sanetschpass": [
    {
      "src": "derivatives/sanetschpass_p0/w1800.webp",
      "credit": "@berniejustlooksaround"
    },
    {
      "src": "derivatives/sanetschpass_p1/w1800.webp",
      "credit": "valaiswallis"
    }
  ],
  "valais#gorges_du_durnand": [
    {
      "src": "derivatives/gorges_du_durnand_p0/w1800.webp",
      "credit": "@travelwithmaria_"
    },
    {
      "src": "derivatives/gorges_du_durnand_p1/w1800.webp",
      "credit": "ivansoko_"
    }
  ],
  "valais#gorges_du_dailley": [
    {
      "src": "derivatives/gorges_du_dailley_p0/w1800.webp",
      "credit": "@hebergements_les_rochers"
    },
    {
      "src": "derivatives/gorges_du_dailley_p1/w1800.webp",
      "credit": "@hebergements_les_rochers"
    },
    {
      "src": "derivatives/gorges_du_dailley_p2/w1800.webp",
      "credit": "vallee_du_trient"
    }
  ],
  "valais#tseuzier_lake": [
    {
      "src": "derivatives/tseuzier_lake_p0/w1800.webp",
      "credit": "@benwe_"
    },
    {
      "src": "derivatives/tseuzier_lake_p1/w1800.webp",
      "credit": "@benwe_"
    },
    {
      "src": "derivatives/tseuzier_lake_p2/w1800.webp",
      "credit": "@steffi_inswiss"
    }
  ],
  "fribourg#gastlosen": [
    {
      "src": "derivatives/gastlosen_p0/w1800.webp",
      "credit": "frdm"
    },
    {
      "src": "derivatives/gastlosen_p1/w1800.webp",
      "credit": "Xavier von Erlach"
    }
  ],
  "fribourg#dent_de_broc": [
    {
      "src": "derivatives/dent_de_broc_p0/w1800.webp",
      "credit": "@danielborloz"
    },
    {
      "src": "derivatives/dent_de_broc_p1/w1800.webp",
      "credit": "ingenieuse.ch"
    },
    {
      "src": "derivatives/dent_de_broc_p2/w1800.webp",
      "credit": "@sherpa__tenzin"
    }
  ],
  "fribourg#dent_de_lys": [
    {
      "src": "derivatives/dent_de_lys_p0/w1800.webp",
      "credit": "@patrick.janser"
    },
    {
      "src": "derivatives/dent_de_lys_p1/w1800.webp",
      "credit": "@patrick.janser"
    },
    {
      "src": "derivatives/dent_de_lys_p2/w1800.webp",
      "credit": "lj.delos"
    }
  ],
  "fribourg#moleson": [
    {
      "src": "derivatives/moleson_p0/w1800.webp",
      "credit": "@markhebertphoto"
    },
    {
      "src": "derivatives/moleson_p1/w1800.webp",
      "credit": "moleson_official"
    },
    {
      "src": "derivatives/moleson_p2/w1800.webp",
      "credit": "myswitzerlandru"
    }
  ],
  "fribourg#teysachaux": [
    {
      "src": "derivatives/teysachaux_p0/w1800.webp",
      "credit": "@o_fargnoli"
    },
    {
      "src": "derivatives/teysachaux_p1/w1800.webp",
      "credit": "fribourgch"
    },
    {
      "src": "derivatives/teysachaux_p2/w1800.webp",
      "credit": "fribourgch"
    }
  ],
  "western#dent_de_jaman": [
    {
      "src": "derivatives/dent_de_jaman_p0/w1800.webp",
      "credit": "Xavier von Erlach"
    },
    {
      "src": "derivatives/dent_de_jaman_p1/w1800.webp",
      "credit": "@guidos.tours"
    },
    {
      "src": "derivatives/dent_de_jaman_p2/w1800.webp",
      "credit": "xavier.paillard"
    }
  ],
  "western#creux_du_van": [
    {
      "src": "derivatives/creux_du_van_p0/w1800.webp",
      "credit": "Daniel R."
    },
    {
      "src": "derivatives/creux_du_van_p1/w1800.webp",
      "credit": "visitsuisse"
    }
  ],
  "western#creux_du_van_ibex": [
    {
      "src": "derivatives/creux_du_van_ibex_p0/w1800.webp",
      "credit": "@jura3lacs"
    },
    {
      "src": "derivatives/creux_du_van_ibex_p1/w1800.webp",
      "credit": "@jura3lacs"
    },
    {
      "src": "derivatives/creux_du_van_ibex_p2/w1800.webp",
      "credit": "@claude_gurzeler"
    }
  ],
  "western#tine_de_conflens": [
    {
      "src": "derivatives/tine_de_conflens_p0/w1800.webp",
      "credit": "@christofs70"
    },
    {
      "src": "derivatives/tine_de_conflens_p1/w1800.webp",
      "credit": "andybuettiker"
    }
  ],
  "western#lac_de_taney": [
    {
      "src": "derivatives/lac_de_taney_p0/w1800.webp",
      "credit": "@alpenliebe_official"
    },
    {
      "src": "derivatives/lac_de_taney_p1/w1800.webp",
      "credit": "@tcheucestbeau"
    },
    {
      "src": "derivatives/lac_de_taney_p2/w1800.webp",
      "credit": "@tcheucestbeau"
    }
  ],
  "western#grammont": [
    {
      "src": "derivatives/grammont_p0/w1800.webp",
      "credit": "@andresduranco"
    },
    {
      "src": "derivatives/grammont_p1/w1800.webp",
      "credit": "bagpictures"
    }
  ],
  "western#st_prex": [
    {
      "src": "derivatives/st_prex_p0/w1800.webp",
      "credit": "@oliwvair1"
    },
    {
      "src": "derivatives/st_prex_p1/w1800.webp",
      "credit": "@oliwvair"
    }
  ],
  "western#marchairuz": [
    {
      "src": "derivatives/marchairuz_p0/w1800.webp",
      "credit": "@jenniferesseiva"
    },
    {
      "src": "derivatives/marchairuz_p1/w1800.webp",
      "credit": "@jenniferesseiva"
    },
    {
      "src": "derivatives/marchairuz_p2/w1800.webp",
      "credit": "@jenniferesseiva"
    }
  ],
  "western#lavaux_vineyards": [
    {
      "src": "derivatives/lavaux_vineyards_p0/w1800.webp",
      "credit": "Razvan Sassu"
    },
    {
      "src": "derivatives/lavaux_vineyards_p1/w1800.webp",
      "credit": "patrykbieganski"
    }
  ],
  "western#etang_de_la_gruere": [
    {
      "src": "derivatives/etang_de_la_gruere_p0/w1800.webp",
      "credit": "@claude_gurzeler"
    },
    {
      "src": "derivatives/etang_de_la_gruere_p1/w1800.webp",
      "credit": "macoooy25"
    },
    {
      "src": "derivatives/etang_de_la_gruere_p2/w1800.webp",
      "credit": "@jura3lacs"
    }
  ],
  "eastern#ascher": [
    {
      "src": "derivatives/ascher_p0/w1800.webp",
      "credit": "Ilia Bronskyi"
    },
    {
      "src": "derivatives/ascher_p1/w1800.webp",
      "credit": "Niklas Tidbury"
    }
  ],
  "eastern#muttseehutte": [
    {
      "src": "derivatives/muttseehutte_p0/w1800.webp",
      "credit": "@jvm_photography"
    },
    {
      "src": "derivatives/muttseehutte_p1/w1800.webp",
      "credit": "@jvm_photography"
    }
  ],
  "eastern#berschnerfall": [
    {
      "src": "derivatives/berschnerfall_p0/w1800.webp",
      "credit": "@sabrina.binkert"
    },
    {
      "src": "derivatives/berschnerfall_p1/w1800.webp",
      "credit": "@sabrina.binkert"
    },
    {
      "src": "derivatives/berschnerfall_p2/w1800.webp",
      "credit": "marcelsiebert_"
    },
    {
      "src": "derivatives/berschnerfall_p3/w1800.webp",
      "credit": "zimydakid"
    }
  ],
  "eastern#the_swiss_dolomites": [
    {
      "src": "derivatives/the_swiss_dolomites_p0/w1800.webp",
      "credit": "@1000schweizerorte"
    },
    {
      "src": "derivatives/the_swiss_dolomites_p1/w1800.webp",
      "credit": "sandro_bedin_landscapes"
    }
  ],
  "eastern#ice_lake_griesslisee": [
    {
      "src": "derivatives/ice_lake_griesslisee_p0/w1800.webp",
      "credit": "@aventouro"
    },
    {
      "src": "derivatives/ice_lake_griesslisee_p1/w1800.webp",
      "credit": "glarnerland.ch"
    }
  ],
  "eastern#gigerwaldsee": [
    {
      "src": "derivatives/gigerwaldsee_p0/w1800.webp",
      "credit": "@aventouro"
    },
    {
      "src": "derivatives/gigerwaldsee_p1/w1800.webp",
      "credit": "patricialang_photography"
    },
    {
      "src": "derivatives/gigerwaldsee_p2/w1800.webp",
      "credit": "patricialang_photography"
    }
  ],
  "eastern#caumasee": [
    {
      "src": "derivatives/caumasee_p0/w1800.webp",
      "credit": "@mattiaantonelliofficial"
    },
    {
      "src": "derivatives/caumasee_p1/w1800.webp",
      "credit": "@mattiaantonelliofficial"
    },
    {
      "src": "derivatives/caumasee_p2/w1800.webp",
      "credit": "flo.jhngtn"
    }
  ],
  "eastern#crestasee": [
    {
      "src": "derivatives/crestasee_p0/w1800.webp",
      "credit": "@signaphoto"
    },
    {
      "src": "derivatives/crestasee_p1/w1800.webp",
      "credit": "flo.jhngtn"
    }
  ],
  "eastern#falensee": [
    {
      "src": "derivatives/falensee_p0/w1800.webp",
      "credit": "@leon.helg"
    },
    {
      "src": "derivatives/falensee_p1/w1800.webp",
      "credit": "Chris Henry"
    }
  ],
  "eastern#morteratsch_glacier": [
    {
      "src": "derivatives/morteratsch_glacier_p0/w1800.webp",
      "credit": "@samir.sparks"
    },
    {
      "src": "derivatives/morteratsch_glacier_p1/w1800.webp",
      "credit": "graubuenden"
    },
    {
      "src": "derivatives/morteratsch_glacier_p2/w1800.webp",
      "credit": "jonglr"
    }
  ],
  "eastern#bovalhutte": [
    {
      "src": "derivatives/bovalhutte_p0/w1800.webp",
      "credit": "@dario_monn"
    },
    {
      "src": "derivatives/bovalhutte_p1/w1800.webp",
      "credit": "mrcgbr"
    }
  ],
  "ticino#ponte_dei_salti": [
    {
      "src": "derivatives/ponte_dei_salti_p0/w1800.webp",
      "credit": "Claudio Schwarz"
    },
    {
      "src": "derivatives/ponte_dei_salti_p1/w1800.webp",
      "credit": "Tom Moser"
    }
  ],
  "ticino#valle_verzasca": [
    {
      "src": "derivatives/valle_verzasca_p0/w1800.webp",
      "credit": "Artiom Vallat"
    },
    {
      "src": "derivatives/valle_verzasca_p1/w1800.webp",
      "credit": "Nadine Marfurt"
    }
  ],
  "ticino#ponte_brolla": [
    {
      "src": "derivatives/ponte_brolla_p0/w1800.webp",
      "credit": "@locarnesetv"
    },
    {
      "src": "derivatives/ponte_brolla_p1/w1800.webp",
      "credit": "@locarnesetv"
    },
    {
      "src": "derivatives/ponte_brolla_p2/w1800.webp",
      "credit": "@locarnesetv"
    }
  ],
  "ticino#valle_verzasca_kayak": [
    {
      "src": "derivatives/valle_verzasca_kayak_p0/w1800.webp",
      "credit": "@noelbell8"
    },
    {
      "src": "derivatives/valle_verzasca_kayak_p1/w1800.webp",
      "credit": "bike2boat.eu"
    }
  ],
  "beyond#mer_de_glace": [
    {
      "src": "derivatives/mer_de_glace_p0/w1800.webp",
      "credit": "Simon Fitall"
    },
    {
      "src": "derivatives/mer_de_glace_p1/w1800.webp",
      "credit": "lerefugedusapi"
    }
  ],
  "beyond#mer_de_glace_winter": [
    {
      "src": "derivatives/mer_de_glace_winter_p0/w1800.webp",
      "credit": "Martin Masson"
    },
    {
      "src": "derivatives/mer_de_glace_winter_p1/w1800.webp",
      "credit": "Ricardo Frantz"
    }
  ],
  "beyond#les_drus_winter": [
    {
      "src": "derivatives/les_drus_winter_p0/w1800.webp",
      "credit": "@robingaillotdrevon"
    },
    {
      "src": "derivatives/les_drus_winter_p1/w1800.webp",
      "credit": "atmb_vivreenhautesavoie"
    }
  ],
  "beyond#aiguille_rouge_reserve": [
    {
      "src": "derivatives/aiguille_rouge_reserve_p0/w1800.webp",
      "credit": "@taufiqsaidi_"
    },
    {
      "src": "derivatives/aiguille_rouge_reserve_p1/w1800.webp",
      "credit": "@taufiqsaidi_"
    }
  ],
  "beyond#mont_blanc": [
    {
      "src": "derivatives/mont_blanc_p0/w1800.webp",
      "credit": "Andrea Caramello"
    },
    {
      "src": "derivatives/mont_blanc_p1/w1800.webp",
      "credit": "Nicolas Weldingh"
    },
    {
      "src": "derivatives/mont_blanc_p2/w1800.webp",
      "credit": "jimmybiggey"
    }
  ],
  "beyond#glacier_des_bossons": [
    {
      "src": "derivatives/glacier_des_bossons_p0/w1800.webp",
      "credit": "@jules_s_photography"
    },
    {
      "src": "derivatives/glacier_des_bossons_p1/w1800.webp",
      "credit": "romainverdure"
    }
  ],
  "beyond#dent_doche": [
    {
      "src": "derivatives/dent_doche_p0/w1800.webp",
      "credit": "@syma_photography"
    },
    {
      "src": "derivatives/dent_doche_p1/w1800.webp",
      "credit": "@syma_photography"
    },
    {
      "src": "derivatives/dent_doche_p2/w1800.webp",
      "credit": "@syma_photography"
    },
    {
      "src": "derivatives/dent_doche_p3/w1800.webp",
      "credit": "@syma_photography"
    }
  ]
};
